// 常量配置：调色板、文案、效果列表与语言选项。/ Static config: palettes, strings, effects, and language options.
import type { Lang, PaletteColor } from "../types";
import { BRAND } from "./brand";

const ALL_LANGS: Lang[] = ["zh-CN", "en"];

/**
 * 生成所有语言同名映射。/ Build a same-label map for all supported languages.
 * @param label 文本标签 / Label text.
 * @returns 语言到文本的映射 / Language-to-label map.
 */
const sameName = (label: string): Record<Lang, string> => {
  const entries = ALL_LANGS.map((lang) => [lang, label]);
  return Object.fromEntries(entries) as Record<Lang, string>;
};

export const PIXEL_SIZES = [3, 4, 5, 6] as const;

export const EFFECTS = ["glitch", "crt", "paletteCycle", "ghost", "ditherFade", "waveWarp"] as const;

export const DIALOG_STYLES = ["win95", "terminal", "dq", "ff", "retro", "neon", "stone", "paper", "void", "aqua"] as const;

export const PALETTES = {
  studio: {
    name: sameName("Studio Dawn"),
    colors: [
      [0, 0, 0],
      [8, 14, 32],
      [22, 32, 60],
      [36, 54, 92],
      [52, 76, 120],
      [72, 104, 152],
      [100, 140, 184],
      [168, 148, 40],
      [220, 200, 90],
      [248, 236, 160],
      [255, 252, 228],
      [224, 160, 128],
    ] as PaletteColor[],
  },
  gameboy: {
    name: sameName("Game Boy"),
    colors: [
      [15, 56, 15],
      [48, 98, 48],
      [139, 172, 15],
      [155, 188, 15],
    ] as PaletteColor[],
  },
  nes: {
    name: sameName("NES"),
    colors: [
      [0, 0, 0],
      [252, 252, 252],
      [188, 188, 188],
      [124, 124, 124],
      [228, 0, 8],
      [248, 56, 0],
      [248, 184, 0],
      [172, 124, 0],
      [0, 184, 0],
      [88, 216, 84],
      [0, 168, 68],
      [0, 232, 216],
      [0, 120, 248],
      [104, 68, 252],
      [216, 0, 204],
      [248, 120, 88],
    ] as PaletteColor[],
  },
  cga: {
    name: sameName("CGA"),
    colors: [
      [0, 0, 0],
      [255, 85, 255],
      [85, 255, 255],
      [255, 255, 255],
    ] as PaletteColor[],
  },
  c64: {
    name: sameName("C64"),
    colors: [
      [0, 0, 0],
      [255, 255, 255],
      [136, 0, 0],
      [170, 255, 238],
      [204, 68, 204],
      [0, 204, 85],
      [0, 0, 170],
      [238, 238, 119],
      [136, 68, 0],
      [102, 68, 0],
      [255, 119, 119],
      [51, 51, 51],
      [119, 119, 119],
      [170, 255, 102],
      [0, 136, 255],
      [187, 187, 187],
    ] as PaletteColor[],
  },
  pico8: {
    name: sameName("PICO-8"),
    colors: [
      [0, 0, 0],
      [29, 43, 83],
      [126, 37, 83],
      [0, 135, 81],
      [171, 82, 54],
      [95, 87, 79],
      [194, 195, 199],
      [255, 241, 232],
      [255, 0, 77],
      [255, 163, 0],
      [255, 236, 39],
      [0, 228, 54],
      [41, 173, 255],
      [131, 118, 156],
      [255, 119, 168],
      [255, 204, 170],
    ] as PaletteColor[],
  },
  sweetie16: {
    name: sameName("Sweetie 16"),
    colors: [
      [26, 28, 44],
      [93, 39, 93],
      [177, 62, 83],
      [239, 125, 87],
      [255, 205, 117],
      [167, 240, 112],
      [56, 183, 100],
      [37, 113, 121],
      [41, 54, 111],
      [59, 93, 201],
      [65, 166, 246],
      [115, 239, 247],
      [244, 244, 244],
      [148, 176, 194],
      [86, 108, 134],
      [51, 60, 87],
    ] as PaletteColor[],
  },
  pastel: {
    name: sameName("Pastel"),
    colors: [
      [255, 179, 186],
      [255, 223, 186],
      [255, 255, 186],
      [186, 255, 201],
      [186, 225, 255],
      [218, 186, 255],
      [255, 186, 243],
      [255, 255, 255],
      [200, 200, 200],
      [120, 120, 120],
      [60, 60, 60],
      [0, 0, 0],
    ] as PaletteColor[],
  },
  mono: {
    name: sameName("Mono"),
    colors: [
      [0, 0, 0],
      [34, 34, 34],
      [68, 68, 68],
      [102, 102, 102],
      [136, 136, 136],
      [170, 170, 170],
      [204, 204, 204],
      [238, 238, 238],
      [250, 250, 250],
    ] as PaletteColor[],
  },
  sepia: {
    name: sameName("Sepia"),
    colors: [
      [44, 28, 6],
      [72, 52, 18],
      [102, 78, 36],
      [138, 110, 60],
      [170, 142, 88],
      [198, 176, 122],
      [222, 204, 160],
      [242, 230, 200],
      [255, 245, 230],
    ] as PaletteColor[],
  },
  sunset: {
    name: sameName("Sunset"),
    colors: [
      [13, 2, 33],
      [44, 6, 69],
      [87, 10, 82],
      [140, 15, 75],
      [191, 36, 51],
      [224, 80, 29],
      [240, 134, 28],
      [248, 190, 53],
      [255, 237, 120],
      [255, 255, 230],
    ] as PaletteColor[],
  },
  ocean: {
    name: sameName("Ocean"),
    colors: [
      [0, 20, 40],
      [0, 40, 80],
      [0, 80, 120],
      [0, 120, 160],
      [0, 160, 200],
      [40, 200, 220],
      [80, 220, 240],
      [160, 240, 255],
      [200, 248, 255],
      [255, 255, 255],
    ] as PaletteColor[],
  },
  earth: {
    name: sameName("Earth"),
    colors: [
      [34, 32, 28],
      [69, 60, 44],
      [107, 95, 70],
      [140, 128, 96],
      [168, 156, 120],
      [96, 128, 56],
      [64, 96, 48],
      [140, 96, 64],
      [192, 160, 112],
      [220, 200, 168],
    ] as PaletteColor[],
  },
  sakura: {
    name: sameName("Sakura"),
    colors: [
      [43, 30, 26],
      [80, 56, 44],
      [52, 80, 48],
      [120, 164, 84],
      [156, 48, 72],
      [200, 80, 108],
      [232, 140, 164],
      [248, 196, 208],
      [255, 232, 238],
      [255, 255, 255],
      [176, 164, 200],
      [140, 180, 220],
    ] as PaletteColor[],
  },
  cyber: {
    name: sameName("Cyber"),
    colors: [
      [8, 4, 16],
      [20, 8, 40],
      [48, 12, 64],
      [100, 20, 100],
      [180, 20, 100],
      [255, 40, 120],
      [255, 140, 200],
      [10, 40, 80],
      [0, 214, 255],
      [80, 240, 255],
      [200, 160, 255],
      [255, 255, 255],
    ] as PaletteColor[],
  },
  horror: {
    name: sameName("Horror"),
    colors: [
      [0, 0, 0],
      [24, 4, 4],
      [60, 8, 8],
      [120, 16, 16],
      [180, 20, 20],
      [220, 60, 40],
      [40, 44, 16],
      [72, 80, 32],
      [48, 24, 48],
      [80, 72, 68],
      [200, 180, 140],
      [240, 220, 190],
    ] as PaletteColor[],
  },
} as const;

export type PaletteId = keyof typeof PALETTES;

const EN_STRINGS: Record<string, string> = {
  menuFile: "File(F)",
  menuEdit: "Edit(E)",
  menuView: "View(V)",
  menuHelp: "Help(H)",
  pixelSize: "SIZE",
  effects: "FX",
  fxPower: "Power",
  fxSpeed: "Speed",
  fxStep: "Step",
  maskTitle: "Mask",
  maskEnable: "Enable Mask",
  maskPaint: "Paint",
  maskErase: "Erase",
  maskToolMode: "Tool Mode",
  maskToolBrush: "Brush",
  maskToolRect: "Rect",
  maskToolLasso: "Lasso",
  maskToolGradient: "Gradient",
  maskFeather: "Feather",
  maskBrush: "Brush",
  maskClear: "Clear",
  maskInvert: "Invert",
  maskOverlay: "Show Overlay",
  presetTitle: "Presets",
  presetName: "Preset Name",
  presetSave: "Save New",
  presetApply: "Apply",
  presetRename: "Rename",
  presetDelete: "Delete",
  presetImport: "Import",
  presetExport: "Export",
  galleryTitle: "Gallery",
  gallerySaveCurrent: "Save Current",
  galleryEmpty: "No local images yet",
  galleryDelete: "Delete",
  galleryClear: "Clear All",
  galleryPrev: "Prev",
  galleryNext: "Next",
  galleryShortcutHint: "Left/Right Arrow",
  gallerySearchPlaceholder: "Search name or tags",
  gallerySelectAll: "Select All",
  galleryUnselectAll: "Unselect",
  galleryBulkDownload: "Bulk Download",
  galleryBulkDelete: "Bulk Delete",
  galleryFavorite: "Favorite",
  galleryTagsPlaceholder: "Tags: city,night",
  galleryTagsApply: "Apply Tags",
  compareToggle: "Compare",
  compareSource: "Original",
  compareProcessed: "Processed",
  compareReset: "Reset View",
  animationTitle: "Animation",
  animationEnable: "Enable Animation",
  animationDuration: "Duration",
  animationProgress: "Progress",
  animationLoop: "Loop",
  animationSetStart: "Set Start",
  animationSetEnd: "Set End",
  animationPlay: "Play",
  animationPause: "Pause",
  animationStop: "Stop",
  projectExport: "Export .pxc",
  projectImport: "Import .pxc",
  performanceMode: "Performance Mode",
  batchZip: "Batch ZIP",
  batchTemplate: "Name Template",
  batchProgress: "Batch Progress",
  batchDownload: "Batch PNG",
  batchProcessing: "Batching...",
  downloadGif: "Download GIF",
  downloadApng: "Download APNG",
  exportGifFps: "GIF FPS",
  exportApngFps: "APNG FPS",
  exportLoopCount: "Loop Count",
  palette: "Palette",
  paletteEditor: "Palette Editor",
  paletteImport: "Import Palette",
  paletteExport: "Export Palette",
  paletteReset: "Reset Palette",
  paletteAddColor: "Add Color",
  paletteExtractCount: "Extract Count",
  paletteMergeThreshold: "Merge Threshold",
  paletteExtract: "Extract Dominant",
  paletteMerge: "Merge Similar",
  paletteLock: "Lock",
  paletteUnlock: "Unlock",
  paletteUnlockAll: "Unlock All",
  fxPipelineTitle: "FX Pipeline",
  fxPipelinePresetName: "Pipeline Preset Name",
  fxPipelinePresetSave: "Save Pipeline",
  fxPipelinePresetApply: "Apply Pipeline",
  fxPipelinePresetDelete: "Delete Pipeline",
  historyTitle: "History",
  historyClear: "Clear History",
  historyEmpty: "No history yet",
  historyItemLabel: "Snapshot",
  dialog: "Dialog",
  onOff: "ON / OFF",
  dialogStyle: "Style",
  dialogName: "Name",
  dialogText: "Text",
  dialogPosition: "Position",
  dialogAdvanced: "Advanced",
  dialogPage: "Page",
  dialogPrev: "Prev",
  dialogNext: "Next",
  dialogTypingSpeed: "Typing Speed",
  dialogAutoPage: "Auto Page",
  dialogAutoDelay: "Auto Delay",
  dialogPageHint: "Use --- on a new line to split pages.",
  fine: "Fine",
  coarse: "Coarse",
  top: "Top",
  bottom: "Bottom",
  dropHint: "Drop",
  orClick: "or click",
  download: "Download PNG",
  downloadVideo: "Download Video",
  recording: "Recording...",
  statusReady: "Waiting",
  statusProcessing: "Processing...",
  statusDone: "Ready",
  statusDrop: "Please drop image",
  statusPresetSaved: "Preset saved",
  statusPresetApplied: "Preset applied",
  statusPresetImported: "Preset imported",
  statusPresetError: "Preset error",
  statusGallerySaved: "Saved to local gallery",
  statusProjectSaved: "Project exported",
  statusProjectLoaded: "Project loaded",
  statusProjectError: "Project file error",
  statusHistoryRestored: "History restored",
  statusHistoryCleared: "History cleared",
  statusHistoryError: "History restore failed",
  statusFxPipelineSaved: "Pipeline preset saved",
  statusFxPipelineApplied: "Pipeline preset applied",
  statusFxPipelineError: "Pipeline preset failed",
  statusPaletteSmartExtracted: "Palette extracted",
  statusPaletteSmartMerged: "Palette merged",
  statusPaletteSmartError: "Palette smart action failed",
  statusExportGifDone: "GIF exported",
  statusExportApngDone: "APNG exported",
  statusFlipbookDisabled: "Flipbook target is not configured",
  legalDisclaimerShort: BRAND.affiliationDisclaimer,
  inspirationCredit: BRAND.inspirationNote,
  about: "About",
  docs: "Docs",
  changelog: "Changelog",
  ghostTitle: BRAND.mascotName,
  start: "Start",
  startPinned: "Pinned",
  startSystem: "System",
  startImportImage: "Import Image",
  startCloseMenu: "Close Menu",
  startSoundOn: "Sound On",
  startSoundOff: "Sound Off",
  taskWindows: "Windows",
  taskNoWindow: "No windows",
  taskReadme: "About",
  taskFlipbook: "Send to Flipbook",
  effect_glitch: "Glitch",
  effect_crt: "CRT",
  effect_paletteCycle: "Cycle",
  effect_ghost: "Ghost",
  effect_ditherFade: "Dither",
  effect_waveWarp: "Wave",
  edit: "Edit",
  pen: "Pen",
  eraser: "Eraser",
  fill: "Fill",
  editorUndo: "Undo",
  editorRedo: "Redo",
  editorSave: "Save",
  editorCancel: "Cancel",
  editorHintPc: "Right-click: Eyedropper / Space+Drag: Pan / Wheel: Zoom",
  style_win95: "Win95",
  style_terminal: "Terminal",
  style_dq: "DQ",
  style_ff: "FF",
  style_retro: "Retro",
  style_neon: "Neon",
  style_stone: "Stone",
  style_paper: "Paper",
  style_void: "Void",
  style_aqua: "Aqua",
  previewTitle: "Preview",
  toolTitle: "Workshop",
  paletteTitle: "Palette",
  dialogTitle: "Dialog",
  docsTitle: "docs.txt",
  changelogTitle: "changelog.txt",
  docsText:
    "Usage\n" +
    "- Drop an image into preview area\n" +
    "- Pick pixel size and palette\n" +
    "- Toggle FX and mask as needed\n" +
    "- Export PNG / Video / .pxc",
  changelogText:
    "v2.0\n" +
    "- Independent branding update\n" +
    "- External links removed by default\n" +
    "- Theme refresh and compliance checks",
  aboutText:
    `${BRAND.appName} ${BRAND.versionLabel}\n` +
    "Independent implementation.\n\n" +
    "- Browser-side processing only\n" +
    "- Pixel resize + palette mapping\n" +
    "- Presets + mask + export tools\n\n" +
    `${BRAND.inspirationNote}\n` +
    `${BRAND.affiliationDisclaimer}`,
};

const ZH_CN_STRINGS: Record<string, string> = {
  ...EN_STRINGS,
  menuFile: "文件(F)",
  menuEdit: "编辑(E)",
  menuView: "视图(V)",
  menuHelp: "帮助(H)",
  fxPower: "强度",
  fxSpeed: "速度",
  fxStep: "步进",
  maskTitle: "蒙版",
  maskEnable: "启用蒙版",
  maskPaint: "涂抹",
  maskErase: "擦除",
  maskToolMode: "工具模式",
  maskToolBrush: "画笔",
  maskToolRect: "矩形",
  maskToolLasso: "套索",
  maskToolGradient: "渐变",
  maskFeather: "羽化",
  maskBrush: "画笔",
  maskClear: "清空",
  maskInvert: "反选",
  maskOverlay: "显示蒙版",
  presetTitle: "预设",
  presetName: "预设名",
  presetSave: "新建保存",
  presetApply: "应用",
  presetRename: "重命名",
  presetDelete: "删除",
  presetImport: "导入",
  presetExport: "导出",
  galleryTitle: "图廊",
  gallerySaveCurrent: "保存当前图",
  galleryEmpty: "暂无本地图片",
  galleryDelete: "删除",
  galleryClear: "清空全部",
  galleryPrev: "上一张",
  galleryNext: "下一张",
  galleryShortcutHint: "左右方向键",
  gallerySearchPlaceholder: "搜索名称或标签",
  gallerySelectAll: "全选",
  galleryUnselectAll: "取消全选",
  galleryBulkDownload: "批量下载",
  galleryBulkDelete: "批量删除",
  galleryFavorite: "收藏",
  galleryTagsPlaceholder: "标签：城市,夜景",
  galleryTagsApply: "保存标签",
  compareToggle: "对比",
  compareSource: "原图",
  compareProcessed: "处理后",
  compareReset: "重置视图",
  animationTitle: "动画",
  animationEnable: "启用动画",
  animationDuration: "时长",
  animationProgress: "进度",
  animationLoop: "循环",
  animationSetStart: "设为起点",
  animationSetEnd: "设为终点",
  animationPlay: "播放",
  animationPause: "暂停",
  animationStop: "停止",
  projectExport: "导出 .pxc",
  projectImport: "导入 .pxc",
  performanceMode: "性能模式",
  batchZip: "批量 ZIP",
  batchTemplate: "命名模板",
  batchProgress: "批处理进度",
  batchDownload: "批量 PNG",
  batchProcessing: "批量处理中...",
  downloadGif: "导出 GIF",
  downloadApng: "导出 APNG",
  exportGifFps: "GIF 帧率",
  exportApngFps: "APNG 帧率",
  exportLoopCount: "循环次数",
  palette: "调色板",
  paletteEditor: "调色板编辑",
  paletteImport: "导入调色板",
  paletteExport: "导出调色板",
  paletteReset: "重置调色板",
  paletteAddColor: "新增颜色",
  paletteExtractCount: "提取数量",
  paletteMergeThreshold: "合并阈值",
  paletteExtract: "提取主色",
  paletteMerge: "合并近色",
  paletteLock: "锁色",
  paletteUnlock: "解锁",
  paletteUnlockAll: "全部解锁",
  fxPipelineTitle: "FX 管线",
  fxPipelinePresetName: "管线预设名",
  fxPipelinePresetSave: "保存管线",
  fxPipelinePresetApply: "应用管线",
  fxPipelinePresetDelete: "删除管线",
  historyTitle: "参数历史",
  historyClear: "清空历史",
  historyEmpty: "暂无历史记录",
  historyItemLabel: "快照",
  dialog: "对话框",
  dialogStyle: "样式",
  dialogName: "名字",
  dialogText: "文本",
  dialogPosition: "位置",
  dialogAdvanced: "高级模式",
  dialogPage: "页",
  dialogPrev: "上一页",
  dialogNext: "下一页",
  dialogTypingSpeed: "打字速度",
  dialogAutoPage: "自动翻页",
  dialogAutoDelay: "翻页延时",
  dialogPageHint: "使用单独一行 --- 进行分页。",
  fine: "精细",
  coarse: "粗糙",
  top: "顶部",
  bottom: "底部",
  dropHint: "拖放",
  orClick: "或点击",
  download: "下载 PNG",
  downloadVideo: "下载视频",
  recording: "录制中...",
  statusReady: "等待",
  statusProcessing: "处理中...",
  statusDone: "就绪",
  statusDrop: "请拖放图片",
  statusPresetSaved: "预设已保存",
  statusPresetApplied: "预设已应用",
  statusPresetImported: "预设已导入",
  statusPresetError: "预设操作失败",
  statusGallerySaved: "已保存到本地图廊",
  statusProjectSaved: "工程已导出",
  statusProjectLoaded: "工程已导入",
  statusProjectError: "工程文件错误",
  statusHistoryRestored: "已回滚到历史节点",
  statusHistoryCleared: "历史已清空",
  statusHistoryError: "历史回滚失败",
  statusFxPipelineSaved: "管线预设已保存",
  statusFxPipelineApplied: "管线预设已应用",
  statusFxPipelineError: "管线预设操作失败",
  statusPaletteSmartExtracted: "调色板主色已提取",
  statusPaletteSmartMerged: "调色板近色已合并",
  statusPaletteSmartError: "调色板智能操作失败",
  statusExportGifDone: "GIF 已导出",
  statusExportApngDone: "APNG 已导出",
  statusFlipbookDisabled: "未配置 Flipbook 目标地址",
  legalDisclaimerShort: "本项目为独立实现，与任何原始站点或作者无隶属关系。",
  inspirationCredit: "灵感来自公开的像素风工具。",
  about: "关于",
  docs: "文档",
  changelog: "更新",
  ghostTitle: "像素机器人",
  startPinned: "常用",
  startSystem: "系统",
  startImportImage: "导入图片",
  startCloseMenu: "关闭菜单",
  startSoundOn: "开启声音",
  startSoundOff: "关闭声音",
  taskWindows: "窗口",
  taskNoWindow: "无窗口",
  taskReadme: "关于",
  taskFlipbook: "发送到 Flipbook",
  effect_glitch: "故障",
  effect_paletteCycle: "色循环",
  effect_ghost: "残影",
  effect_ditherFade: "抖动",
  effect_waveWarp: "波浪",
  edit: "编辑",
  pen: "画笔",
  eraser: "橡皮擦",
  fill: "填充",
  editorUndo: "撤销",
  editorRedo: "重做",
  editorSave: "保存",
  editorCancel: "取消",
  editorHintPc: "右键: 吸管 / Space+拖动: 平移 / 滚轮: 缩放",
  style_terminal: "终端",
  style_retro: "复古",
  style_neon: "霓虹",
  style_stone: "石刻",
  style_paper: "纸本",
  style_void: "虚空",
  style_aqua: "水色",
  previewTitle: "预览",
  toolTitle: "工作台",
  paletteTitle: "调色板",
  dialogTitle: "对话框",
  docsTitle: "文档",
  changelogTitle: "更新日志",
  docsText:
    "使用说明\n" +
    "- 拖入图片到预览区\n" +
    "- 选择像素尺寸和调色板\n" +
    "- 按需开启特效和蒙版\n" +
    "- 导出 PNG / 视频 / .pxc",
  changelogText:
    "v2.0\n" +
    "- 更新为独立品牌表达\n" +
    "- 默认移除外部跳转\n" +
    "- 主题与合规检查增强",
  aboutText:
    `${BRAND.appName} ${BRAND.versionLabel}\n` +
    "- 浏览器本地处理，不上传\n" +
    "- 像素化与调色板映射\n" +
    "- 预设、蒙版与多种导出\n\n" +
    "灵感来自公开的像素风工具。\n" +
    "本项目与任何原始站点或作者无隶属关系。",
};

export const STRINGS: Record<Lang, Record<string, string>> = {
  "zh-CN": ZH_CN_STRINGS,
  en: EN_STRINGS,
};

export const LANG_OPTIONS: Array<{ value: Lang; label: string }> = [
  { value: "zh-CN", label: "简体中文" },
  { value: "en", label: "English" },
];

export const GHOST_MESSAGES: Record<Lang, string[]> = {
  "zh-CN": ["拖入一张图开始处理。", "试试不同调色板组合。", "蒙版可以只让部分区域生效。", "Ctrl+V 可直接粘贴图片。"],
  en: ["Drop an image to begin.", "Try a different palette.", "Mask can target only part of FX.", "You can paste an image with Ctrl+V."],
};
